/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminInvitationsRouteImport } from './routes/_authenticated/admin/invitations'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app/analytics'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppGuestsRouteImport } from './routes/_authenticated/app/guests'
import { Route as AuthenticatedAppLinksRouteImport } from './routes/_authenticated/app/links'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated/app/templates'
import { Route as AuthenticatedAdminCustomersIndexRouteImport } from './routes/_authenticated/admin/customers.index'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin/customers.$id'
import { Route as AuthenticatedAdminCustomersNewRouteImport } from './routes/_authenticated/admin/customers.new'
import { Route as AuthenticatedAppInvitationIndexRouteImport } from './routes/_authenticated/app/invitation.index'
import { Route as AuthenticatedAppInvitationNewRouteImport } from './routes/_authenticated/app/invitation.new'
import { Route as AuthenticatedAppTemplatesCategorySlugRouteImport } from './routes/_authenticated/app/templates.$categorySlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInvitationsRoute =
  AuthenticatedAdminInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppGuestsRoute = AuthenticatedAppGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppLinksRoute = AuthenticatedAppLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAdminCustomersIndexRoute =
  AuthenticatedAdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersNewRoute =
  AuthenticatedAdminCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppInvitationIndexRoute =
  AuthenticatedAppInvitationIndexRouteImport.update({
    id: '/invitation/',
    path: '/invitation/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppInvitationNewRoute =
  AuthenticatedAppInvitationNewRouteImport.update({
    id: '/invitation/new',
    path: '/invitation/new',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTemplatesCategorySlugRoute =
  AuthenticatedAppTemplatesCategorySlugRouteImport.update({
    id: '/$categorySlug',
    path: '/$categorySlug',
    getParentRoute: () => AuthenticatedAppTemplatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/i/$token': typeof ITokenRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/guests': typeof AuthenticatedAppGuestsRoute
  '/app/links': typeof AuthenticatedAppLinksRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRouteWithChildren
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/customers/new': typeof AuthenticatedAdminCustomersNewRoute
  '/app/invitation/new': typeof AuthenticatedAppInvitationNewRoute
  '/app/templates/$categorySlug': typeof AuthenticatedAppTemplatesCategorySlugRoute
  '/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/app/invitation/': typeof AuthenticatedAppInvitationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/i/$token': typeof ITokenRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/guests': typeof AuthenticatedAppGuestsRoute
  '/app/links': typeof AuthenticatedAppLinksRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRouteWithChildren
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/customers/new': typeof AuthenticatedAdminCustomersNewRoute
  '/app/invitation/new': typeof AuthenticatedAppInvitationNewRoute
  '/app/templates/$categorySlug': typeof AuthenticatedAppTemplatesCategorySlugRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersIndexRoute
  '/app/invitation': typeof AuthenticatedAppInvitationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/i/$token': typeof ITokenRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/guests': typeof AuthenticatedAppGuestsRoute
  '/_authenticated/app/links': typeof AuthenticatedAppLinksRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRouteWithChildren
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/customers/new': typeof AuthenticatedAdminCustomersNewRoute
  '/_authenticated/app/invitation/new': typeof AuthenticatedAppInvitationNewRoute
  '/_authenticated/app/templates/$categorySlug': typeof AuthenticatedAppTemplatesCategorySlugRoute
  '/_authenticated/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/_authenticated/app/invitation/': typeof AuthenticatedAppInvitationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/i/$token'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/invitations'
    | '/admin/settings'
    | '/admin/templates'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/guests'
    | '/app/links'
    | '/app/settings'
    | '/app/templates'
    | '/admin/customers/$id'
    | '/admin/customers/new'
    | '/app/invitation/new'
    | '/app/templates/$categorySlug'
    | '/admin/customers/'
    | '/app/invitation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/i/$token'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/invitations'
    | '/admin/settings'
    | '/admin/templates'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/guests'
    | '/app/links'
    | '/app/settings'
    | '/app/templates'
    | '/admin/customers/$id'
    | '/admin/customers/new'
    | '/app/invitation/new'
    | '/app/templates/$categorySlug'
    | '/admin/customers'
    | '/app/invitation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/i/$token'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/invitations'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/templates'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/guests'
    | '/_authenticated/app/links'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/templates'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/customers/new'
    | '/_authenticated/app/invitation/new'
    | '/_authenticated/app/templates/$categorySlug'
    | '/_authenticated/admin/customers/'
    | '/_authenticated/app/invitation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ITokenRoute: typeof ITokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/invitations': {
      id: '/_authenticated/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AuthenticatedAdminInvitationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/guests': {
      id: '/_authenticated/app/guests'
      path: '/guests'
      fullPath: '/app/guests'
      preLoaderRoute: typeof AuthenticatedAppGuestsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/links': {
      id: '/_authenticated/app/links'
      path: '/links'
      fullPath: '/app/links'
      preLoaderRoute: typeof AuthenticatedAppLinksRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/customers/': {
      id: '/_authenticated/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers/new': {
      id: '/_authenticated/admin/customers/new'
      path: '/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AuthenticatedAdminCustomersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/invitation/': {
      id: '/_authenticated/app/invitation/'
      path: '/invitation'
      fullPath: '/app/invitation/'
      preLoaderRoute: typeof AuthenticatedAppInvitationIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/invitation/new': {
      id: '/_authenticated/app/invitation/new'
      path: '/invitation/new'
      fullPath: '/app/invitation/new'
      preLoaderRoute: typeof AuthenticatedAppInvitationNewRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/templates/$categorySlug': {
      id: '/_authenticated/app/templates/$categorySlug'
      path: '/$categorySlug'
      fullPath: '/app/templates/$categorySlug'
      preLoaderRoute: typeof AuthenticatedAppTemplatesCategorySlugRouteImport
      parentRoute: typeof AuthenticatedAppTemplatesRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminInvitationsRoute: typeof AuthenticatedAdminInvitationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
  AuthenticatedAdminCustomersNewRoute: typeof AuthenticatedAdminCustomersNewRoute
  AuthenticatedAdminCustomersIndexRoute: typeof AuthenticatedAdminCustomersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminInvitationsRoute: AuthenticatedAdminInvitationsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
    AuthenticatedAdminCustomersNewRoute: AuthenticatedAdminCustomersNewRoute,
    AuthenticatedAdminCustomersIndexRoute:
      AuthenticatedAdminCustomersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppTemplatesRouteChildren {
  AuthenticatedAppTemplatesCategorySlugRoute: typeof AuthenticatedAppTemplatesCategorySlugRoute
}

const AuthenticatedAppTemplatesRouteChildren: AuthenticatedAppTemplatesRouteChildren =
  {
    AuthenticatedAppTemplatesCategorySlugRoute:
      AuthenticatedAppTemplatesCategorySlugRoute,
  }

const AuthenticatedAppTemplatesRouteWithChildren =
  AuthenticatedAppTemplatesRoute._addFileChildren(
    AuthenticatedAppTemplatesRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppGuestsRoute: typeof AuthenticatedAppGuestsRoute
  AuthenticatedAppLinksRoute: typeof AuthenticatedAppLinksRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRouteWithChildren
  AuthenticatedAppInvitationNewRoute: typeof AuthenticatedAppInvitationNewRoute
  AuthenticatedAppInvitationIndexRoute: typeof AuthenticatedAppInvitationIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppGuestsRoute: AuthenticatedAppGuestsRoute,
  AuthenticatedAppLinksRoute: AuthenticatedAppLinksRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRouteWithChildren,
  AuthenticatedAppInvitationNewRoute: AuthenticatedAppInvitationNewRoute,
  AuthenticatedAppInvitationIndexRoute: AuthenticatedAppInvitationIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ITokenRoute: ITokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
